FROM ubuntu:18.04

LABEL version="1.0"
LABEL description="This container trains a random forest on the iris dataset."
LABEL maintainer="joris.bukala@bigdatarepublic.nl,jacobus.herman@bigdatarepublic.nl"

COPY --chown=root:root ./security/add_user_group.sh ./training_app/requirements.txt /app/
RUN apt-get update -y && \
	apt-get install -y python-pip python-dev && \
	pip install -r /app/requirements.txt && \
	chmod 550 /app/add_user_group.sh && \
	/app/add_user_group.sh && \
	rm /app/add_user_group.sh && \
	rm -rf /var/lib/apt/lists/* && \
	mkdir -p /app/model && \
	chown -R dockerapp:dockerapp /app/model

USER dockerapp

# Copy rest of relevant code
COPY --chown=dockerapp:dockerapp ./training_app /app

ENTRYPOINT [ "python" ]
CMD [ "/app/train.py" ]

# docker run -v ~/Projects/docker_webinar/docker_webinar/docker_example/model:/app/model <image>