FROM nginx:stable-alpine

LABEL version="1.0"
LABEL description="This container is a TLS reverse proxy using Nginx to another container (i.e. sidecar pattern)."
LABEL maintainer="joris.bukala@bigdatarepublic.nl,jacobus.herman@bigdatarepublic.nl"

ENV PROXY_HOST="http://frontend"
ENV PROXY_PORT="4200"

COPY --chown=101:101 ./security/nginx_tls_proxy.template ./security/cert.pem ./security/key.pem /etc/nginx/conf.d/
RUN chmod 775 /etc/nginx/conf.d && \
	find /etc/nginx/conf.d/ -type f -exec chmod 664 -- {} +

EXPOSE 443

CMD [ "/bin/sh", "-c", "envsubst < /etc/nginx/conf.d/nginx_tls_proxy.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'" ]

# docker run -d -p 443:443 <image>