FROM ubuntu:18.04

LABEL version="1.0"
LABEL description="This container trains a random forest on the iris dataset."
LABEL maintainer="name@company.com"

RUN apt-get update -y && \
	apt-get install -y python-pip python-dev

# First just copy requirements to use Docker cache
COPY ./training_app/training_requirements.txt /app/requirements.txt

#WORKDIR /app
RUN pip install -r /app/requirements.txt

# Copy rest of relevant code
COPY ./training_app /app

ENTRYPOINT [ "python" ]
CMD [ "/app/train.py" ]

# docker run -v ~/Projects/docker_webinar/docker_webinar/docker_example/model:/app/model <image>