FROM node:12.16.2

LABEL version="1.0"
LABEL description="This container runs an Angular JS app that connects to a REST API on localhost:5000."
LABEL maintainer="joris.bukala@bigdatarepublic.nl,jacobus.herman@bigdatarepublic.nl"

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY --chown=root:root ./security/add_user_group.sh ./frontend/model-display/package.json /app/
RUN npm install && \
    chmod 550 /app/add_user_group.sh && \
	/app/add_user_group.sh && \
	rm /app/add_user_group.sh

USER dockerapp

COPY --chown=dockerapp:dockerapp ./frontend/model-display /app/

EXPOSE 4200
ENTRYPOINT [ "ng", "serve" ]
CMD [ "--host", "0.0.0.0", "--disableHostCheck", "true" ]